var tipo_veiculos = [
{"nome":"Truck", "id": "truck"},
{"nome":"Toco", "id": "toco"},
{"nome":"Toco 3/4", "id": "toco_34"},
{"nome":"Bi-truck", "id": "bi_truck"},
{"nome":"Só cavalo", "id": "so_cavalo"},
{"nome":"Só cavalo trucado", "id": "so_cavalo_trucado"},
{"nome":"Carreta", "id": "carreta"},
{"nome":"carreta ls", "id": "carreta_ls"},
{"nome":"Bitrem", "id": "bitrem"},
{"nome":"Rodotrem", "id": "rodotrem"},
{"nome":"Bitrenzão", "id": "bitranzao"},
{"nome":"VUC / HR", "id": "vuc_hr"},
{"nome":"Van", "id": "van"},
{"nome":"Utilitário", "id": "utilitario"},
{"nome":"Guinho", "id": "guinho"},
{"nome":"Guindaste", "id": "guindaste"},
{"nome":"Empilhadeira", "id": "empilhadeira"},
{"nome":"Ônibus", "id": "onibus"},
{"nome":"Micro onibus", "id": "micro_onibus"},
{"nome":"Outros", "id": "outros"}];

var tipo_carrocerias = [
{"nome":"Baú", "id": "bau"},
{"nome":"Aberto / Grade baixa", "id": "aberto_grade_baixa"},
{"nome":"Granaleiro / Grade alta", "id": "granaleiro_grade_alta"},
{"nome":"Vanderléia", "id": "vanderleia"},
{"nome":"Frigorífico", "id": "frigorifico"},
{"nome":"Sider", "id": "sider"},
{"nome":"Basculante", "id": "basculante"},
{"nome":"Munck", "id": "munc"},
{"nome":"Prancha", "id": "prancha"},
{"nome":"Plataforma", "id": "plataforma"},
{"nome":"Container", "id": "container"},
{"nome":"Porta container", "id": "porta_container"},
{"nome":"Cegonha", "id": "cegonha"},
{"nome":"Tanque", "id": "tanque"},
{"nome":"Elevação de cargas", "id": "elevacao_de_cargas"},
{"nome":"Transporte de passageiros", "id": "transporte_de_passageiros"},
{"nome":"Outros", "id": "outros"}];
